# Generated by Django 3.0.5 on 2020-05-16 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0003_remove_movies_poster'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='poster',
            field=models.ImageField(default='1000x1481.png', upload_to='images/'),
        ),
    ]
